# -*- coding: utf-8 -*-
"""tarea4jjdr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/jeansdelgado/pagesegmentacion/blob/main/tarea4jjdr.ipynb

### Installing RAG Dependencies

Este bloque de código se encarga de instalar las dependencias necesarias para construir una aplicación de Generación Aumentada por Recuperación (RAG). Utiliza `pip` para instalar varias bibliotecas:

*   `transformers` y `datasets`: Son de Hugging Face y se usan para modelos de procesamiento de lenguaje natural y manejo de conjuntos de datos.
*   `sentence-transformers`: Para crear embeddings (representaciones numéricas) de textos.
*   `faiss-cpu`: Una biblioteca para realizar búsquedas eficientes de similitud en vectores, esencial para la base de datos vectorial de RAG.
*   `langchain-google-genai` y `langchain-community`: Son componentes de LangChain que facilitan la integración con modelos de IA de Google (como Gemini) y proporcionan utilidades para construir aplicaciones basadas en LLM.

También incluye comentarios sobre la instalación opcional de `accelerate` y `bitsandbytes`, que son útiles para optimizar el rendimiento y el uso de memoria con modelos más grandes. Al final, imprime un mensaje de confirmación cuando todas las dependencias se han instalado.
"""



"""### Descarga y Preparación de Documentos

Vamos a descargar el contenido HTML de las URLs proporcionadas y asignaremos los segmentos correspondientes a cada una.
"""

import requests
from bs4 import BeautifulSoup



import gradio as gr
import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
from langchain_google_genai import GoogleGenerativeAIEmbeddings, ChatGoogleGenerativeAI
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
import re # For URL validation
import os
api_key = os.environ.get("GOOGLE_API_KEY")
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY")
# New import for zero-shot classification
from transformers import pipeline

# --- Zero-Shot Classifier Initialization (Global) ---
# Initialize the zero-shot classification pipeline once
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

# Candidate labels for Zero-Shot Classification
segments_options_list = ["Personas", "Emprendedores", "Pymes", "Negocios", "Pyme Social", "Empresas", "Gobiernos", "Prescriptor", "Revendedores","Especificador","Alidos","Proveedores", "Impulsadores","Empleados"]

# Default pages data for the Gradio Dataframe (modified to remove segments column)
default_pages_data_for_df_for_ui = [
    ["https://grupo77.com.ve/about_us.html"],
    ["https://grupo77.com.ve/products.html"],
    ["https://grupo77.com.ve/advantages.html"],
    ["https://grupo77.com.ve/news.html"],
    ["https://grupo77.com.ve/contact.html"],
    ["https://es.tva-automotive.com/"],
    ["https://www.tva-automotive.com/"]  
]

# Helper function to validate URLs
def is_valid_url(url):
    regex = re.compile(
        r'^(?:http|ftp)s?://' # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|' # domain...
        r'localhost|' # localhost...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ...or ip
        r'(?::\d+)?' # optional port
        r'(?:/?|[/?]\S+\.(?:html?|asp|php|jsp|pdf|doc|docx|ppt|pptx|xls|xlsx|txt|xml|json|csv|rtf|zip|rar|jpg|jpeg|png|gif|bmp|tiff|svg|ico)(?:[?#]\S*)?|/?)$', re.IGNORECASE) # Allow various file extensions
    return re.match(regex, url) is not None

def rag_chat(api_key, temperature, selected_model, pages_data_list, chat_history, user_question, progress=gr.Progress()):
    """
    Backend function for the Gradio chatbot. It re-initializes the RAG pipeline
    based on the configuration provided in the Gradio UI.
    """
    progress(0, desc="Iniciando...")

    if not api_key or api_key == "":
    # Intentamos obtener primero GOOGLE_API_KEY
            api_key = os.environ.get("GOOGLE_API_KEY")
    # Configure Gemini API
    try:
        genai.configure(api_key=api_key)
    except Exception as e:
        return chat_history + [{'role': 'user', 'content': user_question}, {'role': 'assistant', 'content': f"❌ Error al configurar la API de Gemini: {e}"}], f"❌ Error al configurar la API de Gemini: {e}", ""

    # Process pages_data_list from Gradio Dataframe (now only contains URLs)
    processed_pages = []
    for row in pages_data_list:
        url_link = row[0] # Only URL now

        if not url_link or not is_valid_url(url_link):
            return chat_history + [{'role': 'user', 'content': user_question}, {'role': 'assistant', 'content': f"❌ URL inválida o vacía en la fila: {row}. Revísala en 'Definir páginas a descargar'."}], f"❌ URL inválida o vacía en la fila: {row}. Revísala en 'Definir páginas a descargar'.", ""

        processed_pages.append({"url": url_link})

    if not processed_pages:
        return chat_history + [{'role': 'user', 'content': user_question}, {'role': 'assistant', 'content': "⚠️ No hay páginas definidas para descargar. Por favor, añade URLs en la barra lateral."}] , "⚠️ No hay páginas definidas para descargar. Por favor, añade URLs en la barra lateral.", ""

    documentos = []
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    progress(0.1, desc="Descargando y procesando documentos...")
    # --- Document Download and Processing ---
    headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "es-ES,es;q=0.9"
    }
    for i, page_info in enumerate(processed_pages):
        url = page_info["url"]
        try:
            response = requests.get(url, headers=headers, timeout=10)
            response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
            html_content = response.text

            soup = BeautifulSoup(html_content, 'html.parser')
            text_content = soup.get_text(separator=' ', strip=True)

            documentos.append({
                "url": url,
                "html_content": html_content,
                "text_content": text_content
            })
            progress(0.1 + 0.2 * (i + 1) / len(processed_pages), desc=f"Procesando {url}...")
        except requests.exceptions.ConnectionError as e:
            print(f"❌ Error de conexión al descargar {url}: {e}")
        except requests.exceptions.Timeout as e:
            print(f"❌ Tiempo de espera agotado al descargar {url}: {e}")
        except requests.exceptions.HTTPError as e:
            print(f"❌ Error HTTP al descargar {url}: {e}")
        except requests.exceptions.RequestException as e:
            print(f"❌ Error de solicitud al descargar {url}: {e}")
        except Exception as e:
            print(f"❌ Un error inesperado ocurrió al procesar la URL {url}: {e}")

    if not documentos:
        return chat_history + [{'role': 'user', 'content': user_question}, {'role': 'assistant', 'content': "⚠️ No se pudo descargar ni procesar ningún documento. Por favor, revisa las URLs."}] , "⚠️ No se pudo descargar ni procesar ningún documento. Por favor, revisa las URLs.", ""

    processed_docs = []
    for doc_info in documentos:
        langchain_doc = Document(
            page_content=doc_info['text_content'],
            metadata={
                "source": doc_info['url'] # No segments in metadata now
            }
        )
        processed_docs.append(langchain_doc)

    progress(0.3, desc="Dividiendo documentos en chunks...")
    chunks = text_splitter.split_documents(processed_docs)

    if not chunks:
        return chat_history + [{'role': 'user', 'content': user_question}, {'role': 'assistant', 'content': "⚠️ No se pudieron generar chunks a partir de los documentos descargados. "
                                               "Asegúrate de que las URLs contienen contenido textual significativo."
                                               "No se encontraron documentos relevantes para su pregunta. Intente con otra." } ], \
               "⚠️ No se pudieron generar chunks a partir de los documentos descargados. " \
               "Asegúrate de que las URLs contienen contenido textual significativo.", ""

    progress(0.4, desc="Generando embeddings...")
    # Initialize embeddings model
    embeddings_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001", google_api_key=api_key)

    progress(0.6, desc="Creando base de datos vectorial FAISS...")
    # Create FAISS vector DB
    vector_db = FAISS.from_documents(chunks, embeddings_model)

    progress(0.8, desc="Configurando LLM y cadena RAG...")
    # Configure LLM
    llm = ChatGoogleGenerativeAI(
        model=selected_model,
        google_api_key=api_key,
        temperature=temperature,
        output_version="v1"
    )

    # Define the RAG prompt
    template = """Responde la pregunta basándose únicamente en el siguiente contexto:
    {context}

    Pregunta: {question}
    """
    prompt = ChatPromptTemplate.from_template(template)

    # Create the RAG chain
    rag_chain = (
        {"context": vector_db.as_retriever(search_kwargs={"k": 3}), "question": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )

    # Invoke the RAG chain
    try:
        progress(0.9, desc="Obteniendo respuesta del LLM...")
        response_text = rag_chain.invoke(user_question)
    except Exception as e:
        return chat_history + [{'role': 'user', 'content': user_question}, {'role': 'assistant', 'content': f"❌ Error al obtener respuesta del LLM: {e}"}], f"❌ Error al obtener respuesta del LLM: {e}", ""

    # Heuristic to determine if the LLM's response is an unsatisfactory answer
    unhelpful_phrases = [
        "no puedo encontrar información",
        "no está disponible en el contexto",
        "no se proporciona esa información",
        "no tengo información sobre",
        "no sé",
        "lo siento",
        "basándome únicamente en el contexto proporcionado, no puedo responder"
    ]

    is_unhelpful = False
    if not response_text.strip(): # Check if response is empty
        is_unhelpful = True
    elif len(response_text.strip()) < 50: # Check if response is too short and might be generic
        is_unhelpful = True
    else:
        for phrase in unhelpful_phrases:
            if phrase in response_text.lower():
                is_unhelpful = True
                break

    if is_unhelpful:
        response_text = (
            "Lo siento, no pude encontrar una respuesta específica a tu pregunta en la información proporcionada "
            "en las páginas de la empresa que tengo acceso. "
            "Mi conocimiento se basa exclusivamente en el contenido de esas páginas web. "
            "Te sugiero que explores directamente la página web o contactes con los canales de comunicación de la empresa "
            "para obtener ayuda más detallada."
        )

    progress(0.95, desc="Clasificando segmentos...")
    # --- Zero-Shot Classification for Segments ---
    classification_results = classifier(user_question, candidate_labels=segments_options_list)

    classified_segments_with_scores = []
    # Sort by score in descending order to pick the most relevant ones first
    sorted_labels_scores = sorted(zip(classification_results['labels'], classification_results['scores']), key=lambda x: x[1], reverse=True)

    # Heuristic: Select segments above a certain threshold (e.g., `temperature` confidence)
    for label, score in sorted_labels_scores:
        if score > temperature:
            classified_segments_with_scores.append(f"{label} ({score:.2f})") # Format label and score

    segments_message = ""
    if classified_segments_with_scores:
        segments_message = "Esta información es válida para los segmentos: " + ", ".join(classified_segments_with_scores) + "."
    else:
        segments_message = (
            "No se pudieron clasificar segmentos específicos para esta pregunta con alta confianza (umbral: "
            f"{temperature:.2f}). Por favor, intente reformular su pregunta o asegúrese de que se alinee con "
            "los segmentos definidos."
        )

    # Format the response for executive output, including segment classification
    executive_response = f"**Respuesta del Agente:**\n\n{response_text}\n\n{segments_message}\n\n---"

    # Update chat history for the Gradio Chatbot component
    chat_history.append({'role': 'user', 'content': user_question})
    chat_history.append({'role': 'assistant', 'content': response_text})

    progress(1, desc="Finalizado.")
    return chat_history, executive_response, "" # Return updated history, formatted response, and clear user input

def clear_all():
    return [], "", os.environ.get('GOOGLE_API_KEY'), 0.2, "gemini-2.5-flash", default_pages_data_for_df_for_ui, ""

# Gradio Interface
with gr.Blocks(title="Chatbot comercial segmentado") as demo:
    gr.Markdown("# 📈 Chatbot comercial segmentado")
    gr.Markdown("Una app sencilla para atención segmentada")

    with gr.Sidebar():
        gr.Markdown("### ⚙️ Configuración")
        gemini_api_key_input = gr.Textbox(label="API Key de Gemini", type="password", info="Introduce tu API Key de Google Gemini.", value=os.environ.get("GEMINI_API_KEY", ""))
        temperature_slider = gr.Slider(minimum=0, maximum=1, step=0.1, value=0.2, label="Temperatura", info="Controla la creatividad del modelo (0=más predecible, 1=más creativo).")
        gr.Markdown("[Obtener API Key](https://aistudio.google.com/api-keys)")

        # Modified pages_dataframe to only include URLs
        pages_dataframe = gr.Dataframe(
            headers=["Link html a descargar"],
            datatype=["str"],
            value=default_pages_data_for_df_for_ui,
            label="Definir páginas a descargar",
            interactive=True,
            type="array",
            col_count=(1, "fixed") # Set col_count to 1 to disable adding/deleting columns
        )
        clear_button = gr.Button("Limpiar Conversación y Reiniciar 🗑️")

    # Main Chatbot interface
    model_selector = gr.Radio(
        ["gemini-2.5-flash"], # Gemini 3.0 Flash is not yet public, but kept as per request for future-proofing
        label="Seleccionar Modelo",
        value="gemini-2.5-flash",
        info="Elige el modelo Gemini para generar respuestas."
    )
    chatbot = gr.Chatbot(label="Chat")

    # Group message input and submit button in a row for better responsiveness
    with gr.Row():
        msg = gr.Textbox(label="Tu pregunta", scale=4)
        submit_btn = gr.Button("Enviar 🚀", scale=1)

    response_output = gr.Textbox(label="Respuesta del Agente (Formato Ejecutivo)", interactive=False, lines=7)

    # Connect components
    submit_btn.click(
        rag_chat,
        inputs=[
            gemini_api_key_input,
            temperature_slider,
            model_selector,
            pages_dataframe,
            chatbot,
            msg
        ],
        outputs=[chatbot, response_output, msg]
    )
    msg.submit(
        rag_chat,
        inputs=[
            gemini_api_key_input,
            temperature_slider,
            model_selector,
            pages_dataframe,
            chatbot,
            msg
        ],
        outputs=[chatbot, response_output, msg]
    )

    clear_button.click(
        clear_all,
        inputs=[],
        outputs=[
            chatbot,
            response_output,
            gemini_api_key_input,
            temperature_slider,
            model_selector,
            pages_dataframe,
            msg
        ]
    )



if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", show_error=True)

